## -*- encoding: utf-8 -*-
## This file (mainNotes_PHS8230.sagetex.sage) was *autogenerated* from mainNotes_PHS8230.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('mainNotes_PHS8230', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
